#!/usr/bin/env bash

set -e

TARGET=${1}
shift

case ${TARGET} in

    java)
        java -jar ${AVRO_TOOLS_JAR} "${@}"
        ;;

    go)
        gogen-avro "${@}"
        ;;

    *)
        echo "Target is unsupported: ${TARGET}"
        exit 1

esac

